
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # Grafana will be available on port 3001
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'  # Set Grafana admin password
    depends_on:
      - prometheus
    restart: always
