name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04 # Explicitly set Ubuntu version
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run build script
      - name: Build Application
        run: npm run build

  test:
    runs-on: ubuntu-22.04 # Explicitly set Ubuntu version
    needs: build
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker-compose build

      # Step 4: Run Tests in Docker
      - name: Run Tests
        run: docker-compose run app npm test

  deploy:
    runs-on: ubuntu-22.04 # Explicitly set Ubuntu version
    needs: test
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Deploy Application Locally with Docker Compose
      - name: Deploy Application
        run: |
          docker-compose down --remove-orphans
          docker-compose up -d
